os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

language: node_js
node_js:
  - "lts/*"
  - "stable"

install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm install
  - npm run bootstrap

before_install:
  - npm install -g node-gyp
  - rm -rf ~/.node-gyp/

script:
  # - npm run lint
  - npm run test-ci

after_script:
  - npm install coveralls@2 -g
  - for file in ./packages/*/coverage/lcov.info; do cat $file | coveralls; done
