os:
  - linux

language: node_js

node_js:
  - "lts/*"
  - "stable"

install:
  - npm install
  - npm run bootstrap

script:
  - npm run lint
  - npm run test-ci

after_script:
  - npm install coveralls@2 -g
  - for file in ./packages/*/coverage/lcov.info; do cat $file | coveralls; done
