environment:
  matrix:
    - nodejs_version: "lts"
    - nodejs_version: "stable"
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install
  - npm run bootstrap
build: off
test_script:
  - node --version
  - npm --version
  - npm run test
version: "{build}"
